In [2]:
import numpy as np
import pandas as pd

# Creating a DataFrame from an Array

In [8]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]

In [9]:
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])
df

      col1  col2
row1     1     2
row2     3     4
row3     5     6

# Creating a DataFrame from a Dictionary

In [2]:
states = ['California', 'Texas','Florida','New York']
population = [656546464,546464646,646465464,642364644]

dict_states = {'States':states,'Populations':population}

df_Population = pd.DataFrame(dict_states)

df_Population

       States  Populations
0  California    656546464
1       Texas    546464646
2     Florida    646465464
3    New York    642364644

## Creating a DataFrame from a CSV (Comma Separated Values) File

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')
# df_exams.head(10)
df_exams.tail(10)

df_exams.shape

(1000, 8)

## Pandas - Attributes

In [4]:
df_exams.shape #This will give the output as (no of rows, no of columnsm)

(1000, 8)

In [5]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [6]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [7]:
df_exams.dtypes #Gives the datatypes of each column

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

## Pandas - Methods

In [8]:
df_exams.head() #This gives datas of the first 5 columns only

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [10]:
df_exams.info() #Shows the info of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [13]:
df_exams.describe() #This give the answers to the basic statistics of the dataframe like mean,std-Standard Deviation,min,max,etc.,

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Select One Column from a DataFrame

## First Method to select one column from a DataFrame

In [4]:
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [5]:
type(df_exams['gender'])

pandas.core.series.Series

In [6]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [8]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## Second Method to select one column from a DataFrame

In [15]:
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [16]:
df_exams["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

## Selecting 2 or more Columns from a DataFrame

In [18]:
df_exams[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [21]:
type(df_exams[['gender','math score']])
# Here there are two pairs of Square Brackets so its type will be a DataFrame
#If there is only one square brackets then it comes under Series type

pandas.core.frame.DataFrame

In [23]:
df_exams[['gender','math score','writing score','reading score']]

     gender  math score  writing score  reading score
0    female          72             74             72
1    female          69             88             90
2    female          90             93             95
3      male          47             44             57
4      male          76             75             78
..      ...         ...            ...            ...
995  female          88             95             99
996    male          62             55             55
997  female          59             65             71
998  female          68             77             78
999  female          77             86             86

[1000 rows x 4 columns]